question_data = [
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Film",
     "question": "Who played Batman in the 1997 film &quot;Batman and Robin&quot;?", "correct_answer": "George Clooney",
     "incorrect_answers": ["Michael Keaton", "Val Kilmer", "Christian Bale"]},
    {"type": "multiple", "difficulty": "hard", "category": "Entertainment: Film",
     "question": "In &quot;Star Trek Nemesis&quot;, why was Praetor Shinzon created?",
     "correct_answer": "To replace Picard as a Romulan Agent",
     "incorrect_answers": ["To destroy the Enterprise", "To become Picard&#039;s friend ", "To steal the Enterprise"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Comics",
     "question": "In the webcomic Homestuck, the first character introduced is Dave Strider.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Music",
     "question": "In 2006, which band released their debut album &quot;A Fever You Can&#039;t Sweat Out&quot;?",
     "correct_answer": "Panic! At the Disco",
     "incorrect_answers": ["Twenty One Pilots", "My Chemical Romance", "Fall Out Boy"]},
    {"type": "multiple", "difficulty": "medium", "category": "Geography",
     "question": "How many countries does Spain have a land border with?", "correct_answer": "5",
     "incorrect_answers": ["2", "3", "4"]}, {"type": "multiple", "difficulty": "easy", "category": "Geography",
                                             "question": "Which nation claims ownership of Antarctica?",
                                             "correct_answer": "No one, but there are claims.",
                                             "incorrect_answers": ["United States of America", "United Nations",
                                                                   "Australia"]},
    {"type": "multiple", "difficulty": "medium", "category": "History",
     "question": "Which country had an &quot;Orange Revolution&quot; between 2004 and 2005?",
     "correct_answer": "Ukraine", "incorrect_answers": ["Belarus", "Latvia", "Lithuania"]},
    {"type": "multiple", "difficulty": "medium", "category": "Celebrities",
     "question": "Nikki Diamond portrayed which Gladiator in the 1992 TV show &quot;Gladiators&quot;?",
     "correct_answer": "Scorpio", "incorrect_answers": ["Jet", "Nightshade", "Falcon"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "The mobile game &quot;Jetpack Joyride&quot; was released in what year? ", "correct_answer": "2011",
     "incorrect_answers": ["2012", "2009", "2014"]},
    {"type": "multiple", "difficulty": "medium", "category": "Politics",
     "question": "What is former United States President Bill Clinton&#039;s full name?",
     "correct_answer": "William Jefferson Clinton",
     "incorrect_answers": ["William Roosevelt Clinton", "William Truman Clinton", "William Lincoln Clinton"]}
]
